name: cipshoe
description: A shoe inventory management application with AI assistant
version: 2.0.0+2

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^6.0.0
  webview_flutter: ^4.10.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
